### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus

### ISSUE THREAD

**Issue by mibby** [xaw3ep/NoCheatPlus#4]
NoCheatPlus compiled as of commit https://github.com/xaw3ep/NoCheatPlus/commit/20fc013b6edbaabda95b3436e4ba58a68434cb8c with commit https://github.com/xaw3ep/NoCheatPlus/commit/b3143bc432fb0f280f84e986464347aed3dfdd51 pulled into the main branch.
ProtocolLib-Gradle dev 14

Noticed these errors after players tried logging in immediately after a server restart.

```
[19:09:24] [Server thread/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$d923d503.getUniqueId(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.players.PlayerDataManager.getPlayerData(PlayerDataManager.java:910) ~[?:?]
	at fr.neatmonster.nocheatplus.players.DataManager.getPlayerData(DataManager.java:204) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.OutgoingPosition.onPacketSending(OutgoingPosition.java:61) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1230) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1158) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1149) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:09:24] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutPosition@9702e27[
    a=-11458.01754064295
    b=76.11934614513807
    c=6466.5791038697425
    d=89.26289
    e=-43.050117
    f=[]
    g=1
  ]

[19:09:24] [Server thread/INFO]: player logged in with entity id 6026 at ([world]-11458.01754064295, 76.11934614513807, 6466.5791038697425)
[19:09:24] [Server thread/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$d923d503.getUniqueId(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.players.PlayerDataManager.getPlayerData(PlayerDataManager.java:910) ~[?:?]
	at fr.neatmonster.nocheatplus.players.DataManager.getPlayerData(DataManager.java:204) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.OutgoingPosition.onPacketSending(OutgoingPosition.java:61) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1230) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1158) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1149) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:09:24] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutPosition@3e477173[
    a=11528.519628100488
    b=68.0
    c=-5885.647949939987
    d=-51.885498
    e=22.650414
    f=[]
    g=1
  ]

[19:09:24] [Server thread/INFO]: player logged in with entity id 6089 at ([world]11528.519628100488, 68.0, -5885.647949939987)
[19:09:25] [Server thread/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$d923d503.getUniqueId(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.players.PlayerDataManager.getPlayerData(PlayerDataManager.java:910) ~[?:?]
	at fr.neatmonster.nocheatplus.players.DataManager.getPlayerData(DataManager.java:204) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.OutgoingPosition.onPacketSending(OutgoingPosition.java:61) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1230) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1158) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1149) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:09:25] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutPosition@508c9c8f[
    a=5.096104214879036
    b=116.0
    c=-0.03951974393986829
    d=141.88861
    e=10.349985
    f=[]
    g=1
  ]
```

**Comment by xaw3ep** [comment]
Sorry for late response, I can't reproduce it

**Comment by mibby** [comment]
It only occurs when forcefully reconnecting players after a restart by proxying and caching connections on BungeeCord . As if NCP registered them as temp players until they were fully loaded on the server. Once the server has settled after the restart (~30 seconds), it doesn't occur anymore.

**Comment by xaw3ep** [comment]
Oh I see, haven't tried with Bungee yet, just tried without it

**Comment by mibby** [comment]
Happened again with NCP as of commit https://github.com/xaw3ep/NoCheatPlus/commit/94ed22789c2feef73991bcb121a68bc710accc50

Here is the full "post" start-up log to give you an idea.
https://paste.ubuntu.com/p/N7pTvCp5JY/

**Comment by xaw3ep** [comment]
Not sure it fixed or not as I don't have the plugin require Protocollib to create fake players for some pre-check, will be temporarily closed
